services:
  gather-prometheus-exporter:
    image: "djbasster/gather-prometheus-exporter:develop"
    build:
      context: .
    ports:
      - "127.0.0.1:9991:9991"
    volumes:
      - .:/app
    env_file:
      - .env
    entrypoint: ['yarn', "start:dev"]
